### ISSUE TITLE
lc test

### ISSUE THREAD

**Issue by lijenn** [lijenn/testing#4]
https://lucid.app/documents/view/9deba07d-fd20-4cab-bd5e-e1dbf1bcfb3d

**Comment by lijenn** [comment]
https://lucid.app/documents/view/9deba07d-fd20-4cab-bd5e-e1dbf1bcfb3d

**Comment by lijenn** [comment]
### Co-planning

1a:
- [ ] Initiate/Send Co-plan 1a Email
- [ ] Schedule Co-plan 1a

If 1b is needed:
- [ ] Follow-up by sending Co-plan 1b email
- [ ] Schedule co-plan 1b 

2a:
- [ ] Initiative/Send Co-Plan 2a email
- [ ] Schedule Co-plan 2a
- [ ] Get the team meeting date/time and members and clinical roles from the Process map, unless 2b is needed. 

If 2b is needed:
- [ ] Follow up by sending Co-plan 2b email
- [ ] Schedule Co-plan 2b
- [ ] Get the team meeting date/time and members and clinical roles from the Process map. 

### Team Meeting Prep
- [ ] List out team dates/times
- [ ] Send Team Times to EES and request TMS Code
- [ ] EES confirms TMS course code and times are added to TMS
- [ ] Check TMS course listing/code for errors
- [ ] Set up MS Teams Group and add Learners
- [ ] Send Outlook invitations for team meetings to Learners from MTL.Help@va.gov
- [ ] Setup team folders on mtl.how/data 
- [ ] Prep Pre/post emails 
- [ ] Prep Baseline and 6 month follow up surveys

### NIH Red
NIH Red Part I
- [ ] Send Pre-email
- [ ] Confirm EES for CMEs/CEUs 
- [ ] Send Post-email
- [ ] Send Baseline Survey

NIH Red Part II
- [ ] Send Pre-email
- [ ] Confirm EES for CMEs/CEUs
- [ ] Send Post-email
- [ ] Send 6 month follow up survey in 6 months from last team meeting

### VA Red Session 1-12:

### NIH/VA Blue Session 1-12:

NIH/VA Blue Session 1:
- [ ] Send Pre-email
- [ ] Confirm EES for CMEs/CEUs 
- [ ] Send Post-email
- [ ] Send Baseline Survey
- [ ] Email and schedule meeting with the MTL Team Lead to prep data for Session 2. 

NIH/VA Blue Session 2:
- [ ] Prep Sim UI and MTL Menu logins for Learners and Facilitators.

NIH/VA Blue Session 3:

NIH/VA Blue Session 4:
- [ ] Prep and send Team Time report #1, attach to post email.

NIH/VA Blue Session 5:

NIH/VA Blue Session 6:

NIH/VA Blue Session 7:

NIH/VA Blue Session 8:
- [ ] Prep and send Team Time report #2, attach to post email. 

NIH/VA Blue Session 9:

NIH/VA Blue Session 10:

NIH/VA Blue Session 11:

NIH/VA Blue Session 12:
- [ ] Send Pre-email
- [ ] Confirm EES for CMEs/CEUs
- [ ] Send Post-email
- [ ] Send 6 month follow up survey in 6 months from last team meeting
- [ ] Prep and send Team Time report #3, attach to post email. 
- [ ] Send MTL goodies to Learners.
